### ISSUE TITLE
I need some help

### ISSUE THREAD

**Issue by pabloleone** [modess/php-jenkins#3]
I'm facing an issue I cannot figure out why. 

This folder /var/lib/jenkins/workspace/Credenciales/build/ exists and this other /var/lib/jenkins/workspace/Credenciales/build/logs also.

I set 777 persmission to all folders and files.

I followed this guide https://modess.io/jenkins-php/

Still failing, graphs are empty.

Helps is very appreciated.

`
BUILD FAILED
/var/lib/jenkins/workspace/Credenciales/build.xml:168: exec returned: 2

Total time: 1 minute 5 seconds
Build step 'Invoke Ant' marked build as failure
[WARNINGS] Parsing warnings in console log with parser PHP Runtime
[CHECKSTYLE] Collecting checkstyle analysis files...
[CHECKSTYLE] Finding all files that match the pattern build/logs/checkstyle.xml
[PMD] Collecting PMD analysis files...
[PMD] Finding all files that match the pattern build/logs/pmd.xml
[DRY] Collecting duplicate code analysis files...
[DRY] Finding all files that match the pattern build/logs/pmd-cpd.xml
Recording plot data
Publishing Clover coverage report...
Publishing Clover HTML report...
Publishing Clover XML report...
Publishing Clover coverage results...
[CRAP4J] Collecting Crap4J analysis files...
[CRAP4J] Searching for report files within build/logs/crap4j.xml
[CRAP4J] Using the new FileSetBuilder
[CRAP4J] Got a report bean with 161 crap methods out of 3834 methods.
[htmlpublisher] Archiving HTML reports...
[htmlpublisher] Archiving at BUILD level /var/lib/jenkins/workspace/Credenciales/build/api to /var/lib/jenkins/jobs/Credenciales/builds/11/htmlreports/API_Documentation
ERROR: Directory '/var/lib/jenkins/workspace/Credenciales/build/api' exists but failed copying to '/var/lib/jenkins/jobs/Credenciales/builds/11/htmlreports/API_Documentation'.
[xUnit] [INFO] - Starting to record.
[xUnit] [INFO] - Processing PHPUnit-3.x (default)
[xUnit] [INFO] - [PHPUnit-3.x (default)] - 1 test report file(s) were found with the pattern 'build/logs/junit.xml' relative to '/var/lib/jenkins/workspace/Credenciales' for the testing framework 'PHPUnit-3.x (default)'.
[xUnit] [INFO] - Check 'Failed Tests' threshold.
[xUnit] [INFO] - The total number of tests for this category exceeds the specified 'failure' threshold value.
[xUnit] [INFO] - Setting the build status to FAILURE
[xUnit] [INFO] - Stopping recording.
[JDepend] JDepend plugin is ready
[JDepend] Couldn't generate JDepend file at 'build/logs/jdepend.xml'java.io.FileNotFoundException: /var/lib/jenkins/workspace/Credenciales/build/logs/jdepend.xml (No such file or directory)
Finished: FAILURE`

**Comment by modess** [comment]
It seems that you have unit tests that fail, and that is causing the build to fail. If you run phpunit on your local machine, do all tests pass?

**Comment by mhellmeier** [comment]
Got the same problem.
I have no failing phpunit tests.

I think the problem is that htmlpublisher can't copy files. My log file:
`[htmlpublisher] Archiving at BUILD level /[PATH]/workspace/build/api to /[PATH]/builds/14/htmlreports/API_Documentation
ERROR: Directory '/[PATH]/workspace/build/api' exists but failed copying to '/[PATH]/builds/14/htmlreports/API_Documentation'.
ERROR: This is especially strange since your build otherwise succeeded.
Build step 'Publish HTML reports' changed build result to FAILURE`
After a little bit of searching, I found this question but it doen't helped me: https://stackoverflow.com/questions/15360733/jenkins-job-fails

I got the JDepend error, too:
`[JDepend] JDepend plugin is ready
[JDepend] Couldn't generate JDepend file at 'build/logs/jdepend.xml'java.io.FileNotFoundException: /[PATH]/workspace/build/logs/jdepend.xml (No such file or directory)`

(I replaced my path mit [PATH] for this issue).
