### ISSUE TITLE
Missing files 

### ISSUE THREAD

**Issue by jhfaber** [modess/php-jenkins#6]
Hi i am installing jenkins-laravel continuos integration, but i see missing files:

there is the file:
phpunit-bootstrap.php (PHPUnit bootstrap script)

It's a problem? i'don't see this in the git

**Comment by modess** [comment]
I assume you're following the guide you found here: https://modess.io/continuous-integration-for-laravel-with-jenkins-and-git/?

I have since updated that guide since it's outdated (written in 2012), you can find the new guide here: https://modess.io/jenkins-php/. Try that and let me know if you can't get it to work.

**Comment by jhfaber** [comment]
It´s work! thanks!!

**Comment by modess** [comment]
Happy to hear that! :)
